server:
  port: 20990

spring:
  application:
    name: salesken-universal-encoder

  profiles:
    active: dev

ok-http:
  connection-properties:
    connect-timeout: 20000
    write-timeout: 20000
<<<<<<< HEAD
    read-timeout: 20000
=======
    read-timeout: 20000


tf:
  api:
    encoder:
      url: http://localhost:8080/tf/encode
>>>>>>> Initial commit
