server:
  port: 20990

spring:
  application:
    name: salesken-universal-encoder

  profiles:
    active: default

ok-http:
  connection-properties:
    connect-timeout: 20000
    write-timeout: 20000
    read-timeout: 20000